CREATE TABLE usuario(
	id INT NOT NULL AUTO_INCREMENT,
    username VARCHAR(100) NOT NULL,
    bike VARCHAR(100) NOT NULL,
    voption VARCHAR(100) NOT NULL,
    houses VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);